$ErrorActionPreference='Stop'
$R=Resolve-Path (Join-Path $PSScriptRoot '..')
$Boot=Join-Path $R 'src/runtime/runtime_boot_windows.c'
if(!(Test-Path $Boot)){throw "missing $Boot"}
$S=Get-Content -Raw -Encoding UTF8 $Boot
function Has([string]$Needle,[string]$Label){if(!$S.Contains($Needle)){throw "missing $Label"}}
function Lacks([string]$Needle,[string]$Label){if($S.Contains($Needle)){throw "forbidden $Label"}}
$CountDefine='#define DEADWIRE_'+'SMOKE_REQUESTS 8'
Has $CountDefine 'eight live requests'
Has 'static uint64_t client_context[8];' 'response table client context'
Has 'static const char health_get_request[] = "GET /health HTTP/1.0' 'health get request'
Has 'static const char health_head_request[] = "HEAD /health HTTP/1.0' 'health head request'
Has 'static const char missing_get_request[] = "GET /missing HTTP/1.0' 'missing get request'
Has 'static const char root_get_request[] = "GET / HTTP/1.0' 'root get request'
Has 'static const char css_get_request[] = "GET /style.css HTTP/1.0' 'css get request'
Has 'deadwire_set_response(health_response_context' 'health response context'
Has 'deadwire_set_response(root_response_context' 'root response context'
Has 'deadwire_set_response(css_response_context' 'css response context'
Has 'deadwire_set_response(missing_response_context' 'missing response context'
Has 'client_context[3] = 0;' 'empty selected response slot'
Has 'client_context[4] = (uint64_t)health_response_context;' 'health response slot'
Has 'client_context[5] = (uint64_t)root_response_context;' 'root response slot'
Has 'client_context[6] = (uint64_t)css_response_context;' 'css response slot'
Has 'client_context[7] = (uint64_t)missing_response_context;' 'missing response slot'
Has 'static int deadwire_run_probe_request(struct sockaddr_in *bound_addr, int request_index)' 'live request probe'
Has 'if (client_context[3]) {' 'starts without selected response'
Has 'peer_socket = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);' 'real peer socket'
Has 'if (connect(peer_socket, (struct sockaddr *)bound_addr, sizeof(*bound_addr)))' 'real peer connect'
Has 'if (send(peer_socket, request, request_length, 0) != request_length)' 'real peer send'
Has 'if (dw_runtime_mode_bound(mode_context))' 'runtime mode path'
Has 'if (client_context[3] != expected_response)' 'runtime selected response check'
Has 'if (!deadwire_contains(response_buffer, received, expected_status, expected_status_length))' 'status check'
Has 'if (!deadwire_contains(response_buffer, received, health_connection' 'connection close check'
Has 'if (!deadwire_contains(response_buffer, received, expected_type_line, expected_type_line_length))' 'content type check'
Has 'if (!deadwire_contains(response_buffer, received, expected_length, expected_length_length))' 'content length check'
Has 'if (!deadwire_contains(response_buffer, received, expected_body, expected_body_length))' 'body check'
Has 'deadwire_response_has_body(response_buffer, received)' 'head no body check'
Has 'expected_cursor = (uint64_t)((request_index + 1) % DEADWIRE_QUEUE_CAPACITY);' 'queue cursor check'
Has 'for (i = 0; i < DEADWIRE_'+'SMOKE_REQUESTS; ++i)' 'bounded request loop'
Has 'server_addr.sin_port = 0;' 'ephemeral local port'
Has 'if (dw_runtime_live_open(live_context))' 'live open path'
Has 'result = deadwire_run_long_mode(&server_addr);' 'long mode live run'
$Select='dw_runtime_'+'select_client_response(client_context'
Lacks $Select 'boot-side response preselection'
Lacks 'selected_route' 'boot-side route variable'
Write-Output 'verify-v2livepath: ok'
